# Generated by Django 5.2.7 on 2026-01-31 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'calendar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'flashcard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'habit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('pomodoro_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=36)),
                ('work_duration', models.IntegerField()),
                ('break_duration', models.IntegerField()),
                ('current_session', models.CharField(max_length=36)),
                ('sessions_completed', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pomodoro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.CharField(blank=True, max_length=6, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('todolist_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'todolist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('role', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=8, null=True)),
                ('repeat_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('priority', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.calendar')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.task')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('reminder_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('remind_type', models.CharField(blank=True, max_length=12, null=True)),
                ('is_sent', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.event')),
            ],
            options={
                'db_table': 'event_reminder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flashcardset',
            fields=[
                ('set_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flashcard')),
            ],
            options={
                'db_table': 'flashcardset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flashcarditem',
            fields=[
                ('card_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('learned', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flashcardset')),
            ],
            options={
                'db_table': 'flashcarditem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Habitlist',
            fields=[
                ('habitlist_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('daily_target', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.habit')),
            ],
            options={
                'db_table': 'habitlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pomodorohistory',
            fields=[
                ('history_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('study_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pomodoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pomodoro')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.task')),
            ],
            options={
                'db_table': 'pomodorohistory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Todolistgroup',
            fields=[
                ('group_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.todolist')),
            ],
            options={
                'db_table': 'todolistgroup',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.todolistgroup'),
        ),
        migrations.CreateModel(
            name='UsersAvatar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.user')),
                ('path', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'db_table': 'users_avatar',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AddField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.CreateModel(
            name='Habitlistlog',
            fields=[
                ('log_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=32)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
                ('habitlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.habitlist')),
            ],
            options={
                'db_table': 'habitlistlog',
                'managed': True,
                'unique_together': {('habitlist', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Flashcardprogress',
            fields=[
                ('progress_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.flashcarditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
            ],
            options={
                'db_table': 'flashcardprogress',
                'managed': True,
                'unique_together': {('card', 'user')},
            },
        ),
    ]
